function raster(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 21-Sep-2015 12:40:39

% Create figure
figure1 = figure;
colormap(flipud(gray));

% Create axes
axes1 = axes('Parent',figure1,'YDir','reverse','Layer','top');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 90.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 540.5]);
box(axes1,'on');
hold(axes1,'all');

% Create image
image(cdata1,'Parent',axes1);

% Create xlabel
xlabel('Time (1s bins)','FontSize',14);

% Create ylabel
ylabel('Neuron #','FontSize',14);

% Create title
title({'Spike Raster','Color: Spks/Neuron/bin'},'FontSize',16);

% Create colorbar
colorbar('peer',axes1,'LineWidth',1);

